In [ ]:
import torch

In [ ]:
if torch.cuda.is_available():
  print("its availables")

its available


In [ ]:
torch.empty(2,3)

tensor([[-3.2794e-36,  4.3984e-41, -6.8479e+08],
        [ 3.3403e-41,  0.0000e+00,  0.0000e+00]])

In [ ]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [ ]:
torch.rand(2,3)

tensor([[0.7978, 0.9769, 0.5658],
        [0.5269, 0.7003, 0.2391]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
x = torch.tensor([[1,2,3],[1,2,3]])

In [ ]:
x

tensor([[1, 2, 3],
        [1, 2, 3]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[134812650054800, 134808492547104, 134812238649840],
        [134812650283216, 134812238649840, 134812651559280]])

In [ ]:
x.dtype

torch.int64

In [ ]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [1., 2., 3.]])